# Collected from https://github.com/Lornatang/SRGAN-PyTorch
# =========================================================


# experiment name
EXP_NAME: test
# random number seed
SEED: 0
# super resolution magnification factor
SCALE: 8
# run device model
DEVICE_ID: 1

# default: inductor, which may be better, but it is not supported by the P100 GPU in Bracewell
BACKEND: eager
# BACKEND: aot_eager
# BACKEND: inductor

# Model define
MODEL:
  EMA:
    ENABLE: True
    DECAY: 0.999
    COMPILED: True
  G:
    NAME: srresnet_x8
    IN_CHANNELS: 1
    OUT_CHANNELS: 1
    CHANNELS: 64
    NUM_RCB: 16
    COMPILED: False
    FREEZE: False
  D:
    NAME: discriminator_for_vgg
    IN_CHANNELS: 1
    OUT_CHANNELS: 1
    CHANNELS: 64
    COMPILED: False
    FREEZE: False

TRAIN:
  DATASET:
    TRAIN_GT_IMAGES_DIR: ./data/Allen-Cahn_Periodic-BC_reaction_diffusion_advection/train/mesh_63
    TRAIN_LR_IMAGES_DIR: ./data/Allen-Cahn_Periodic-BC_reaction_diffusion_advection/train/mesh_7
    GT_IMAGE_SIZE: 64
    IMG_TYPE: npy
    HAS_SUBFOLDER: True
    INDEX_VAL_MAPPING: ./data/Allen-Cahn_Periodic-BC_reaction_diffusion_advection/index-val-mapping.csv

  # Model file address, used for pre-training and recovery training
  CHECKPOINT:
    # PRETRAINED_G_MODEL: ./results/pretrained_models/SRResNet_x8-SRGAN_ImageNet.pth.tar
    PRETRAINED_G_MODEL: ./results/pretrained_models/SRGAN_x8-SRGAN_ImageNet.pth.tar
    PRETRAINED_D_MODEL: ""
    RESUMED_G_MODEL: ""
    RESUMED_D_MODEL: ""

  # training hyperparameters
  HYP:
    EPOCHS: 100

    IMGS_PER_BATCH: 16
    SHUFFLE: True
    NUM_WORKERS: 4
    PIN_MEMORY: True
    PERSISTENT_WORKERS: True

  OPTIM:
    NAME: Adam
    LR: 0.001
    BETAS: [ 0.9, 0.999 ]
    EPS: 0.0001
    WEIGHT_DECAY: 0.0

  LR_SCHEDULER:
    NAME: MultiStepLR
    MILESTONES: [ 9 ]
    GAMMA: 0.5

  # Loss function
  LOSSES:
    PIXEL_LOSS:
      NAME: MSELoss
      WEIGHT: [ 1.0 ]
    CONTENT_LOSS:
      NAME: ContentLoss
      NET_CFG_NAME: "vgg19"
      BATCH_NORM: False
      NUM_CLASSES: 2
      MODEL_WEIGHTS_PATH: "one-channel" # means load and modify the weights
      FEATURE_NODES: [ "features.35" ]
      FEATURE_NORMALIZE_MEAN: [ 0.485 ]
      FEATURE_NORMALIZE_STD: [ 0.229 ]
      WEIGHT: [ 1.0 ]
      IN_CHANNELS: 3
    ADVERSARIAL_LOSS:
      NAME: vanilla
      WEIGHT: [ 0.001 ]
    PHYSICS_LOSS:
      NAME: MSELoss
      INNER_WEIGHT: [ .00000001 ] # the original val is  .000000001
      BOUNDARY_WEIGHT: [ 5 ]

  PRINT_PER_BATCH: False
  PRINT_BATCH_FREQ: 100

TEST:
  DATASET:
    PAIRED_TEST_GT_IMAGES_DIR: ./data/Allen-Cahn_Periodic-BC_reaction_diffusion_advection/validation/mesh_63
    PAIRED_TEST_LR_IMAGES_DIR: ./data/Allen-Cahn_Periodic-BC_reaction_diffusion_advection/validation/mesh_7
    IMG_TYPE: npy
    HAS_SUBFOLDER: True

  # Test hyperparameters
  HYP:
    IMGS_PER_BATCH: 1
    SHUFFLE: False
    NUM_WORKERS: 1
    PIN_MEMORY: True
    PERSISTENT_WORKERS: True

  # Only test Y channel
  ONLY_TEST_Y_CHANNEL: False

  SAVE_IMAGE_DIR: ./results/validation/
  
  # saving the difference between the ground truth and the prediction
  SAVE_IMAGE_DIFF_DIR: ""